

version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: notify_x
    command: sh -c "python manage.py runserver 0.0.0.0:8010"
    volumes:
      - ./:/app
      - ./static:/app/static
      - ./media:/app/media
    ports:
      - 8010:8010
    restart: "on-failure"
    environment:
      - ENV=DEV
