# Generated by Django 5.1.2 on 2024-10-19 22:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('recipients', models.TextField(help_text='Enter emails separated by a comma')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('send_instantly', models.BooleanField(default=False)),
                ('schedule_date', models.DateTimeField(blank=True, help_text='Specify date/time for scheduled email', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repeat', models.BooleanField(default=False)),
                ('repeat_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='weekly', help_text='Set the frequency of reminders', max_length=20)),
                ('repeat_until', models.DateTimeField(blank=True, help_text='End date for repeat reminders', null=True)),
                ('repeat_max_times', models.IntegerField(default=0, help_text='Max number of times to send reminder. 0 for unlimited')),
                ('next_reminder_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reminder_day', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], help_text='Day of the week for weekly reminders', max_length=9)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminder.email')),
            ],
        ),
    ]
