# Generated by Django 5.1.2 on 2024-10-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColdEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('recipients', models.TextField(help_text='Enter emails separated by commas')),
                ('instant_send', models.BooleanField(default=False)),
                ('scheduled_time', models.DateTimeField(blank=True, help_text='Set this if sending later', null=True)),
                ('reminder_period', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly')], help_text='Set for recurring reminders', max_length=20, null=True)),
                ('max_reminders', models.IntegerField(default=1, help_text='Number of reminder emails to be sent')),
                ('times_sent', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('day_of_week', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=9, null=True)),
                ('specific_datetime', models.DateTimeField(blank=True, help_text='Set if you want a one-time reminder', null=True)),
                ('repeat', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='reminder',
            name='email',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
