# Generated by Django 4.0 on 2024-10-20 02:57

from django.db import migrations, models
import django.utils.timezone
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_coldemail_personalreminder_remove_reminder_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColdEmailReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipients', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body', markdownx.models.MarkdownxField()),
                ('instant_send', models.BooleanField(default=False)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('reminder_frequency', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('custom', 'Custom')], max_length=10, null=True)),
                ('max_reminders', models.IntegerField(default=1)),
                ('sent_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalEmailReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('body', markdownx.models.MarkdownxField()),
                ('repeat_option', models.BooleanField(default=False)),
                ('scheduled_day_of_week', models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Friday', 'Friday')], max_length=10, null=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='ColdEmail',
        ),
        migrations.DeleteModel(
            name='PersonalReminder',
        ),
    ]
