# Generated by Django 4.0 on 2024-10-21 01:31

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0003_coldemailreminder_personalemailreminder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coldemailreminder',
            name='reminder_template',
            field=markdownx.models.MarkdownxField(default=''),
            preserve_default=False,
        ),
    ]
