# Generated by Django 4.0 on 2024-10-21 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0005_remove_personalemailreminder_repeat_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coldemailreminder',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coldemailreminder',
            name='max_reminders',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='coldemailreminder',
            name='reminder_frequency',
            field=models.CharField(choices=[('same_day', 'Same Day'), ('daily', 'Daily'), ('after_1_day', 'After 1 Day'), ('after_2_days', 'After 2 Days'), ('after_3_days', 'After 3 Days'), ('weekly', 'Weekly'), ('no_reminder', 'No Reminder')], default='no_reminder', max_length=15),
        ),
        migrations.CreateModel(
            name='ColdEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date', models.DateField()),
                ('sent_time', models.TimeField(auto_now_add=True)),
                ('email_reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminder.coldemailreminder')),
            ],
        ),
    ]
