# Generated by Django 4.0 on 2024-10-21 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0006_coldemailreminder_reminder_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_date', models.DateField()),
                ('sent_time', models.TimeField(auto_now_add=True)),
                ('email_reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminder.personalemailreminder')),
            ],
        ),
    ]
