# Generated by Django 4.0 on 2024-10-21 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0007_personalemaillog'),
    ]

    operations = [
        migrations.AddField(
            model_name='coldemailreminder',
            name='failure_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personalemailreminder',
            name='failure_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='personalemailreminder',
            name='sent_count',
            field=models.IntegerField(default=0),
        ),
    ]
