# Generated by Django 4.0 on 2024-10-22 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0008_coldemailreminder_failure_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coldemaillog',
            name='is_reminder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coldemailreminder',
            name='reminder_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coldemailreminder',
            name='reminder_failure_count',
            field=models.IntegerField(default=0),
        ),
    ]
