# Generated by Django 4.0 on 2024-10-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0009_coldemaillog_is_reminder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coldemailreminder',
            name='simple_body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
