# Generated by Django 4.0 on 2024-10-22 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0010_coldemailreminder_simple_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coldemailreminder',
            name='simple_body',
        ),
    ]
