# Generated by Django 4.0 on 2024-10-22 17:59

from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0011_remove_coldemailreminder_simple_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='coldemailreminder',
            name='plain_body',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coldemailreminder',
            name='plain_reminder_template',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='coldemailreminder',
            name='body',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
        migrations.AlterField(
            model_name='coldemailreminder',
            name='reminder_template',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
