# Generated by Django 4.0 on 2024-10-22 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0014_alter_coldemailreminder_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coldemaillog',
            name='deactivate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coldemailreminder',
            name='deactivate',
            field=models.BooleanField(default=False),
        ),
    ]
