# Generated by Django 4.0 on 2024-10-23 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0016_alter_coldemailreminder_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coldemailreminder',
            name='plain_body',
        ),
        migrations.RemoveField(
            model_name='coldemailreminder',
            name='plain_reminder_template',
        ),
    ]
