# Generated by Django 4.0 on 2024-10-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0017_remove_coldemailreminder_plain_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coldemaillog',
            name='deactivate',
        ),
        migrations.AddField(
            model_name='personalemailreminder',
            name='deactivate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='personalemailreminder',
            name='scheduled_day_of_week',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('All days', 'All days')], help_text='For recurring emails. Select the day(s) of the week on which to send the email.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='personalemailreminder',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, help_text='For one-time Email only. Choose this if the email is to be sent at a specific date and time.', null=True),
        ),
        migrations.AlterField(
            model_name='personalemailreminder',
            name='scheduled_time_of_day',
            field=models.TimeField(blank=True, help_text='Time of day to send the email if a recurring day is selected.', null=True),
        ),
    ]
