# Generated by Django 4.0 on 2025-03-07 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0018_remove_coldemaillog_deactivate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coldemaillog',
            name='message_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
