# Generated by Django 4.0 on 2025-04-04 18:07

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0019_coldemaillog_message_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', ckeditor_uploader.fields.RichTextUploadingField()),
                ('is_default', models.BooleanField(default=False)),
                ('message_type', models.CharField(choices=[('main', 'Main Email'), ('reminder', 'Reminder Email')], help_text='Is this for the main email or a reminder?', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Message Template',
                'verbose_name_plural': 'Message Templates',
            },
        ),
        migrations.CreateModel(
            name='SubjectTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='Reusable subject line for emails.', max_length=255)),
                ('is_default', models.BooleanField(default=False, help_text='Mark this subject as default.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subject Template',
                'verbose_name_plural': 'Subject Templates',
            },
        ),
        migrations.AddField(
            model_name='coldemailreminder',
            name='main_message_template',
            field=models.ForeignKey(blank=True, help_text='Select a reusable message template for the main email.', limit_choices_to={'message_type': 'main'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_reminders', to='reminder.messagetemplate'),
        ),
        migrations.AddField(
            model_name='coldemailreminder',
            name='reminder_message_template',
            field=models.ForeignKey(blank=True, help_text='Select a reusable message template for reminder emails.', limit_choices_to={'message_type': 'reminder'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminder_reminders', to='reminder.messagetemplate'),
        ),
        migrations.AddField(
            model_name='coldemailreminder',
            name='subject_template',
            field=models.ForeignKey(blank=True, help_text='Choose a predefined subject template.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_reminders', to='reminder.subjecttemplate'),
        ),
    ]
