# Generated by Django 4.0 on 2025-04-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0020_messagetemplate_subjecttemplate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coldemailreminder',
            name='subject',
            field=models.CharField(blank=True, help_text='Enter the subject of the email.', max_length=255, null=True),
        ),
    ]
