# Generated by Django 4.0 on 2025-04-04 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0021_alter_coldemailreminder_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalemailreminder',
            name='notification_method',
            field=models.CharField(choices=[('email', 'Email Only'), ('telegram', 'Telegram Only'), ('both', 'Email and Telegram')], default='email', help_text='Choose how you want to be notified.', max_length=10),
        ),
        migrations.AddField(
            model_name='personalemailreminder',
            name='subject_template',
            field=models.ForeignKey(blank=True, help_text='Select a predefined subject template. Takes precedence over the custom subject field.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_reminders', to='reminder.subjecttemplate'),
        ),
        migrations.AddField(
            model_name='personalemailreminder',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Telegram chat ID of the user (used if Telegram or Both is selected).', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personalemailreminder',
            name='recipient',
            field=models.EmailField(help_text='Used only if Email or Both is selected.', max_length=254),
        ),
        migrations.AlterField(
            model_name='personalemailreminder',
            name='scheduled_day_of_week',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday'), ('All days', 'All days')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='personalemailreminder',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalemailreminder',
            name='scheduled_time_of_day',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personalemailreminder',
            name='subject',
            field=models.CharField(blank=True, help_text='Used if a subject template is not selected.', max_length=255),
        ),
    ]
