# Generated by Django 4.0 on 2025-04-04 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0022_personalemailreminder_notification_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalemailreminder',
            name='telegram_chat_id',
        ),
    ]
