# Generated by Django 4.0 on 2025-04-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0023_remove_personalemailreminder_telegram_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalemailreminder',
            name='recipient',
            field=models.EmailField(blank=True, help_text='Used only if Email or Both is selected.', max_length=254),
        ),
    ]
