# Generated by Django 4.0 on 2025-04-04 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0024_alter_personalemailreminder_recipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='resumes/')),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='coldemailreminder',
            name='resume',
            field=models.FileField(blank=True, help_text='Optionally upload a custom resume.', null=True, upload_to='custom_resumes/'),
        ),
        migrations.AddField(
            model_name='coldemailreminder',
            name='resume_template',
            field=models.ForeignKey(blank=True, help_text='Or select a resume from the library.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='reminder.resume'),
        ),
    ]
