# Generated by Django 4.0 on 2025-04-04 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0025_resume_coldemailreminder_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coldemailreminder',
            name='has_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coldemailreminder',
            name='last_checked_for_reply',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
