# Generated by Django 4.0 on 2024-10-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_blogitem_options_alter_chip_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('start_date', models.CharField(max_length=20)),
                ('end_date', models.CharField(max_length=20)),
                ('tasks', models.JSONField()),
                ('order', models.IntegerField(default=0)),
                ('skills', models.ManyToManyField(to='portfolio.Chip')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
