# Generated by Django 4.0 on 2024-10-28 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_workexperience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='tasks',
        ),
        migrations.CreateModel(
            name='WorkExperienceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('work_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='portfolio.workexperience')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
