# Generated by Django 4.0 on 2024-10-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_remove_workexperience_tasks_workexperiencetask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogitem',
            name='banner_image',
            field=models.FileField(blank=True, null=True, upload_to='project_banners/'),
        ),
        migrations.AlterField(
            model_name='projectitem',
            name='banner_image',
            field=models.FileField(blank=True, null=True, upload_to='project_banners/'),
        ),
    ]
