# Generated by Django 4.0 on 2024-10-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_blogitem_banner_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('about_me', models.TextField()),
                ('image', models.ImageField(upload_to='profile_images/')),
                ('linkedin_url', models.URLField(blank=True, max_length=255, null=True)),
                ('github_url', models.URLField(blank=True, max_length=255, null=True)),
                ('facebook_url', models.URLField(blank=True, max_length=255, null=True)),
                ('stackoverflow_url', models.URLField(blank=True, max_length=255, null=True)),
                ('instagram_url', models.URLField(blank=True, max_length=255, null=True)),
                ('intro_video', models.FileField(blank=True, null=True, upload_to='intro_videos/')),
                ('intro_characteristics', models.JSONField(default=list)),
            ],
        ),
    ]
