# Generated by Django 4.0 on 2024-10-28 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_technology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='image',
        ),
        migrations.AddField(
            model_name='technology',
            name='file',
            field=models.FileField(default='', upload_to='technology_files/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='technology',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
