# Generated by Django 4.0 on 2024-11-11 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_remove_technology_image_technology_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogitem',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectitem',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='technology',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
